version: '3'

networks:
    net:
        driver: bridge

services: 
    simple-nodejs-server:
        image: "simple-nodejs-server:latest"
        container_name: "simple-nodejs-server"
        ports:
            - "8080:8080"
        networks:
            - scs
            
    mongo:
        image: mongo
        ports:
        - "27017:27017"
    